### ISSUE TITLE
Latest Alpine images break SQL CLI build

### ISSUE THREAD

**Issue by mrsarm** [rust-lang/docker-rust#167]
Not sure whether this is an issue related to changes in how the **Rust Alpine image** is generated, but I'm able to build the latest version of `sqlx-cli` without problems in older versions of Alpine with Docker, and with my local Ubuntu machine using latest Rust as well.

Using a not so old Alpine image `rust:1.71-alpine3.18` the following Dockerfile works:

```Dockerfile
FROM rust:1.71-alpine3.18

RUN apk add --no-cache --purge openssl-dev musl-dev \
    && cargo install sqlx-cli \
         --target x86_64-unknown-linux-musl \
         --no-default-features \
         --features native-tls,postgres

ENTRYPOINT ["/usr/local/cargo/bin/sqlx"]
```

I can build the executable, and run a container with the resulting image:

```sh
# Build with:
docker build -t sqlx-cli .
# ...
# Run with:
docker run -it --rm sqlx-cli --version
sqlx-cli 0.7.3
```

Changing the image to `rust:1.72-alpine3.18`, `rust:1.73-alpine3.18` or the latest Alpine version `rust:1.74.1-alpine3.18` the build fails with the following:

```sh
docker build -t sqlx .

...
53.02    Compiling sqlx v0.7.3
53.06    Compiling sqlx-cli v0.7.3
...
80.60 
80.76 error: could not compile `sqlx-cli` (bin "cargo-sqlx") due to previous error
80.76 warning: build failed, waiting for other jobs to finish...
81.08 error: linking with `cc` failed: exit status: 1
81.08   |
81.08   = note: LC_ALL="C" PATH="/usr/local/rustup/toolchains/1.74.1-x86_64-unkn...
...
80.60   = note: /usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssl: No such file or directory
80.60           /usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lcrypto: No such file or directory
80.60           collect2: error: ld returned 1 exit status
80.60           
80.60 
80.76 error: could not compile `sqlx-cli` (bin "cargo-sqlx") due to previous error
80.76 warning: build failed, waiting for other jobs to finish...
81.08   |
...
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache --purge openssl-dev musl-dev     && cargo install sqlx-cli          --target x86_64-unknown-linux-musl          --no-default-features          --features native-tls,postgres" did not complete successfully: exit code: 101
```

CC @abonander @mehcode

**Comment by Muscraft** [comment]
I tried adding  `openssl-libs-static` and it appeared to work. Modify your `apk add` to be:
```
apk add pkgconfig libc-dev openssl-dev openssl-libs-static
```

**Comment by polarathene** [comment]
> Still the same issue with the `rust:1.76.0-alpine` image. You can't use the `openssl-sys` crate

You can if you do it properly: https://github.com/sfackler/rust-openssl/issues/1627#issuecomment-1958587430

```bash
# Rust alpine container with extra deps added:
docker run --rm -it rust:alpine ash
apk add musl-dev openssl-dev openssl-libs-static

# Minimal project example:
cargo init /example && cd /example
cargo add openssl

# All one command (can paste into terminal without needing `\`)
cat > src/main.rs <<EOF
fn main() {
    println!("Version: {}", openssl::version::version());
}
EOF

# Check builds successfully:
cargo run --release
# OUTPUT:
# Version: OpenSSL 3.1.4 24 Oct 2023
```

You can replace my `main.rs` example with your own and use the `openssl-sys` crate directly instead of `openssl` and that still works correctly.

---

> This is weird because both `/usr/lib/libssl.so` and `/usr/lib/libcrypto.so` exists and you can compile and link a C program

> If we don't use the provided docker image, but manually install rust into the `alpine` docker image, everything works:

> I tried adding `openssl-libs-static` and it appeared to work.

The C program worked because you dynamically linked, while the rust target `x86_64-unknown-linux-musl` differs from it's `*-gnu` equivalent, it statically links by default (_`-C target-feature=+crt-static`_) and is self contained (_`-C link-self-contained=yes`, this provides `crti.o` from the rust toolchain instead of distro libs_).

The reason it's different when you use the official alpine image directly is because you installed cargo from `apk` right? Not rustup? They patch their package to dynamically link by default and IIRC it has a different target (_`x86_64-alpine-linux-musl` or something like that_). There are plans in the future AFAIK to make the `*-musl` targets dynamic by default to avoid that confusion, but I've no idea when that may actually land.

---

So there's your answer :)

- `rust:alpine` => static linked
- `alpine` => dynamic linked

If you want to use `rust:alpine` and dynamic link you could use `RUSTFLAGS='-C target-feature=-crt-static' cargo build` 👍

**Comment by tyilo** [comment]
@polarathene Thanks for the explanation, that makes perfect sense.

It is quite weird that `rust:alpine` uses statically linking by default, but alpine's own rust doesn't.
But I guess that will be fixed with https://github.com/rust-lang/rust/issues/59302

<hr>

@mrsarm's issue can also be fixed by either installing `openssl-libs-static` or using dynamic linking, so maybe this should be closed?

**Comment by mrsarm** [comment]
Thanks all for the feedback and workarounds, I'll test them Today or Tomorrow and post here the results.

**Comment by mrsarm** [comment]
Worked !

So for those that need the same, here is the example again fixed, and with the latest Rust image available Today:

```Dockerfile
FROM rust:1.76-alpine3.19

RUN apk update \
    && apk add --no-cache --purge openssl-dev openssl-libs-static musl-dev libc-dev \
    && cargo install sqlx-cli \
         --target x86_64-unknown-linux-musl \
         --no-default-features \
         --features native-tls,postgres

ENTRYPOINT ["/usr/local/cargo/bin/sqlx"]
```

This is how to build it, and test it:

```sh
# Build with:
docker build -t sqlx-cli .
# ...
# Run with:
docker run -it --rm sqlx-cli --version
sqlx-cli 0.7.3
```
